// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";

export default {
  schema: "prisma/schema.prisma",
  datasource: {
    url: `file:${path.join(process.cwd(), "dev.db")}`,
  },
};
